name: Custom Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: 'Build'

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |- 
        docker login --username 
        docker build . --file Dockerfile --tag dice-scroller-admin:$(date +%s)